### ISSUE TITLE
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/graalvm/collections/EconomicMapImpl

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/benerator-maven-plugin#1]
Following Exception after successful run ...

Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/graalvm/collections/EconomicMapImpl$3
	at org.graalvm.collections.EconomicMapImpl.iterator(EconomicMapImpl.java:846)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.collectAliveContexts(PolyglotEngineImpl.java:1177)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureClosed(PolyglotEngineImpl.java:1067)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$PolyglotShutDownHook.run(PolyglotEngineImpl.java:1396)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.graalvm.collections.EconomicMapImpl$3
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)

**Comment by ake2l** [comment]
After in thread "main" system.exit(0) is called ... thread "Thread-3" is started to shutdown  PolyglotEngineImpl ... this is only an issue when I run benerator.main as mojo

**Comment by vbergmann2** [comment]
I think the cleanest and most universal solution is a JVM shutdown hook, that calls  org.graalvm.nativeimage.VMRuntime.shutdown() like this:

	Runtime.getRuntime().addShutdownHook(new Thread() {
		public void run() 
			logger.debug(„Running shutdown hook“);
			org.graalvm.nativeimage.VMRuntime.shutdown();
		}
	});
}

**Comment by ake2l** [comment]
Unfortunately it does not help, because i am not using the graalvm native image and i just figured out, it has something to do with the already existing shutdown hook of  `com.oracle.truffle.polyglot.PolyglotEngineImpl$PolyglotShutDownHook.run(PolyglotEngineImpl.java:1396)` , this one is called after shutdown but in the middle of this method `void ensureClosed(boolean cancelIfExecuting, boolean inShutdownHook)` the class-path seems to be gone . My idea was to disable this hook by any available options when creating the engine, but unfortunately there seems to be no way.

**Comment by ake2l** [comment]
This known shutdown Exception will be suppressed now.
